anoubisd sfs.c bug fix
The fedora 8 gcc gives:
In function 'open',
inlined from 'sfs_create_upgradeindex' at sfs.c:729,
inlined from 'sfs_writesfsdata' at sfs.c:897:
/usr/include/bits/fcntl2.h:51: error: call to '__open_missing_mode' declared with attribute error: open with O_CREAT in second
argument needs 3 arguments
cc1: warnings being treated as errors
In function 'memset',
inlined from '__sfs_checksumop' at sfs.c:344:
/usr/include/bits/string3.h:82: warning: call to '__warn_memset_zero_len' declared with attribute warning: memset used with
constant zero length parameter; this could be due to transposed parameters

Aegis-Change: anoubis.10.971.C229 Delta 53
BLE